version: '3.8'
services:
  app:
    container_name: api
    env_file:
      - .env
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
    restart: unless-stopped
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gituzh
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/psql:/var/lib/postgresql/data:z
  nats:
    image: nats:2.10.11
    container_name: nats
    command: [
      "-js",          
      "-sd", "/data", 
      "-m", "8222"   
    ]
    ports:
      - 4222:4222 
      - 8222:8222
    volumes:
      - ./docker/nats:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
